## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# question 1.1
import pandas as pd
import numpy as np

data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

frame = pd.DataFrame(data)
print(df)

# question 1.2 
print("people with a job of either psychologist or teacher, and have more cars than the people in their family:")
print(frame[((frame["job"] == "psychologist") | (frame["job"] == "teacher")) | (frame["num_cars"] >= (frame["family_size"]))])

# question 1.3 
print("people with a family bigger than three, and at least one car:")
print(frame[((frame["family_size"] > 3 ) & (frame["num_cars"] > 0 ))])

# question 1.4 
numberJobsUnique = frame["job"].nunique()
print("the number of jobs are" , str(numberJobsUnique))




     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
people with a job of either psychologist or teacher, and have more cars than the people in their family
     name             job  family_size  num_cars
0  Joseph         teacher            3         3
1   Jacob    psychologist            2         1
2     Sam  data scientist            1         1
4    Ryan    psychologist            2         2
5    Lisa    psychologist            3         4
6     Lee         teacher            2         1
people with a family bigger than three, and at least one car
    name                 job  family_size  num_cars
3  Jesee  softwa

**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
#original code
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
import numpy as np
#imported pandas as well to use the pd.series command
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

#i made a fruits list originally, and then appended the 10 random fruits that the randomizer chose
fruitList = []
fruitList.append(fruit) 
print("This is the list of fruits the randomizer chose: ", fruitList)

#i did the same for the weights to make a list, then printed it out so you can see what they are
weightsList = []
weightsList.append(weights)
print("This is the list of weights: ", weightsList)

weights.groupby(fruit).mean()

This is the list of fruits the randomizer chose:  [0    carrot
1     apple
2     apple
3     apple
4    carrot
5     apple
6     apple
7    banana
8    carrot
9     apple
dtype: object]
This is the list of weights:  [0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64]


apple     5.333333
banana    8.000000
carrot    5.000000
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
# original code
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# question 3.1
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
indicesElements = np.sort(course_name)
print("These are the indices for the course names: ", str(indicesElements))

These are the indices for the course names:  ['JS' 'PHP' 'Python' 'examples' 'html']


In [ ]:
# question 3.2
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
namesP = np.char.startswith(course_name, "P")
print(namesP)

[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# question 4.1
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
reversedStudents = student_id[::-1]
print("Here is the original array: ", str(student_id))
print("Here is the reversed array: ", str(reversedStudents))


here is the original array:  [1023 5202 6230 1671 1682 5241 4532]
here is the reversed array:  [4532 5241 1682 1671 6230 5202 1023]


In [ ]:
# question 4.2 
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_id.sort()
print("the highest student_id values are: ", str(student_id[3:6]))

the highest student_id values are:  [4532 5202 5241]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

# Hint: you can use arange to start off
print("multiples of three: ")
multThree = np.arange(0, 100, 3)
print(multThree)
sumThree = sum(multThree)
print(sumThree)
print(" ")

print("multiples of five: ")
multFive = np.arange(0, 100, 5)
print(multFive)
sumFive = sum(multFive)
print(sumFive)

total = sumFive + sumThree

print("total sum is : ", str(total))

multiples of three: 
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
1683
 
multiples of five: 
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
950
total sum is :  2633


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
#original
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#question 6.1
import numpy as np 

arr = np.arange(12).reshape(3,4)
arr[:, [1, 2]] = arr[:, [2, 1]] 
print(arr)

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


In [ ]:
# question 6.2
import numpy as np

arr = np.arange(12).reshape(3,4)
arr[[0, 1]] = arr[[1, 0]]
print(arr)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
